language: node_js
before_script:
  - npm install -g lab
deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: "AKIAI3KL3QKDGWZQFMUA"
    secret_access_key: "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"
    bucket: ""
    key: "latest/MyApp.zip"
    application: MyApp
    deploydment_group: MyDeploydmentGroup
    skip_cleanup: true
    on:
      branch: master
      all_branches: false
