language: node_js
deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: ""
    secret_access_key: ""
    bucket: ""
    key: "latest/MyApp.zip"
    application: MyApp
    deploydment_group: MyDeploydmentGroup
    skip_cleanup: true
    on:
      branch: master
      all_branches: false
